### ISSUE TITLE
Remove enableDebug

### ISSUE THREAD

**Issue by SEJeff** [graphite-project/whisper#101]
this function does some nastiness such as using globals to override open() and there isn't currently a way to disable it once enabled.

As a maintainer, I don't personally see a ton of utility in it and would be more in favor of removing it from whisper's master branch and 0.10 as a result. For profiling times I'd rather just use cProfile and the excellent runsnake Python profile viewer instead.

What does the rest of the team think of this? Any utility in keeping it around? If so, I can make a disableDebug, but it would have to add more grotesque globals and that is generally poor programming practice.

**Comment by toni-moreno** [comment]
I have just used it to understand some internal behavior of whisper engine on developing this PR (https://github.com/graphite-project/whisper/pull/120) ... IMHO there is necessary to keep some kind of debug

**Comment by SEJeff** [comment]
If it is useful to a contributor who hacks on whisper, it is useful to the project. Closing
