### ISSUE TITLE
Whisper lacks testcases and is not time invariant

### ISSUE THREAD

**Issue by JensRantil** [graphite-project/whisper#11]
I'm filing this issue since I've been thinking about this for a while. Not sure if I should report this here or on Launchpad.

Some time ago I contributed to Whisper. I was curious to see how whisper worked, and I also wanted to add more powerful import functionality of historical data. I've also considered using Whisper to store historical data in production.

Looking at the code there were two things that bothered me:
 1. **The total lack of test cases.** I am not necessarily that guy who always require everything to have testcases or 100% test coverage. More so, I think it's *more important to test only what needs to be tested*. However, there are two reasons why I think Whisper needs at least a couple of crucial test cases (but tests for corner cases should preferably be added, too):
  * It will store my precious historical data and I will blindly trust all data that's been stored in Whisper. There seem to be a number of corner cases (esp. due to 2)). I truly hope that these corner cases will never show up as regressions in the future.
  * It will make it waay easier for newcomers to confidently contribute to Whisper.
 2. **It is time dependent.** There are multiple calls to `time.time()` done in multiple places. This makes it harder to recreate corner cases, write tests and also [identify corner cases](https://github.com/graphite-project/whisper/pull/10).

I'd love to hear your input on this. If this is not something you are willing to work on in Whisper, maybe it's something that can brought to attention in Ceres.

**Comment by SEJeff** [comment]
Really tempted to close this as the rest coverage is now over 80% for the whisper lib (not the scripts that come with it just yet)

**Comment by JensRantil** [comment]
@sejeff I'm fine with that. This was a somewhat unclear issue, but I'm happy it was taken seriously. Probably better to create individual issues for separate tasks.

**Comment by SEJeff** [comment]
I spent a pretty good effort upping the coverage over the holidays but I'd love some help! Regarding the time.time() bits please open another issue and I'll take a look at it.

Thanks!
