### ISSUE TITLE
(bug) whisper-resize.py tool inserts holes in lower precision archives 

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/whisper#121]
Hi everyone.

I've been testing for a while the whisper-resize tool. As you can see in the following picture the resized whisper file has holes at the 2 lowest precision archives (blue and brown lines)

![image](https://cloud.githubusercontent.com/assets/5883405/6142768/51a2e6d4-b1bd-11e4-8e47-8f07eb3e2da1.png)

To test it I've made 2 new tools in this PR https://github.com/graphite-project/whisper/pull/120 
- **whisper-createfull.py** who can create whisper files with a single value in alls its datapoints and enables us to know the expected data after resized
-  **whisper-split.py** anables create as many whisper files as archives in the original whisper file so we can inspect data contained in each archive file.

We did the following test:
- create a know whisper file (all values= 1.0) with a know retention ( 1m:30d and 15m: 365d) 
- resize the original file to a lowest retention ( by example )
- split the resized whisper file. ( expected data is to be all values = 1.0 in all the archives )
- plot all data in each archive with a external tool like grafana ( we did a scale(metric_archive,num) to represent in the graph lowest precision archives values with a line below highest precision, with this representation we can see easily where data exist and it's value.

you can reproduce this test executing this script.

```
#! /bin/bash
WHISPER_DIR = /opt/grafito/storage/whisper/
rm -f $WHISPER_DIR/whisper_test_file*
whisper-createfull.py $WHISPER_DIR/whisper_test_file.wsp 60: 30d 15m: 365d
whisper-resize.py $WHISPER_DIR/whisper_test_file.wsp --newfile = $WHISPER_DIR/whisper_test_file_resized.wsp 1m: 30d 5m: 90d 1h: 200d 1d: 1a
whisper-split.py $WHISPER_DIR/whisper_test_file_resized.wsp
```

These are the results when plotted each archive with a line over the other (scale)

![image](https://cloud.githubusercontent.com/assets/5883405/6142709/df7d6df0-b1bb-11e4-80fd-63791af02cea.png).

**Comment by deniszh** [comment]
@toni-moreno - are you still able to reproduce that?
BTW we have carbonate repo now, so, https://github.com/graphite-project/whisper/pull/120 can be ported there.

**Comment by toni-moreno** [comment]
Hi @deniszh I have no enough time to spend in this test, but as I said before you can reproduce the error with  these tools  https://github.com/graphite-project/whisper/pull/120 and with this script.

```
#! /bin/bash
WHISPER_DIR = /opt/grafito/storage/whisper/
rm -f $WHISPER_DIR/whisper_test_file*
whisper-createfull.py $WHISPER_DIR/whisper_test_file.wsp 60: 30d 15m: 365d
whisper-resize.py $WHISPER_DIR/whisper_test_file.wsp --newfile = $WHISPER_DIR/whisper_test_file_resized.wsp 1m: 30d 5m: 90d 1h: 200d 1d: 1a
whisper-split.py $WHISPER_DIR/whisper_test_file_resized.wsp
````
after you can plot each splited file one on top the other to see where the holes are located.  Thank you for review this issue !
