### ISSUE TITLE
Migrate historical data with aggregation

### ISSUE THREAD

**Issue by Neway6655** [graphite-project/whisper#124]
I met a data migration issue here, for instance, I have some historical metric keys: metrics.node1.request.count
metrics.node2.request.count
...
metrics.node8.request.count

And I need to aggregate(sum) those metrics to metrics.all.request.count, is there any script can help me to do that? 

Thanks a lot!

**Comment by bensusman** [comment]
Is there currently a recommended solution for this kind of issue or does this require implementing still?

**Comment by deniszh** [comment]
I do not know about solution to that either...
