### ISSUE TITLE
whisper logo

### ISSUE THREAD

**Issue by kyzh** [graphite-project/whisper#128]
It would be nice to have a logo for whisper.
I would make good use of it in my documentation diagrams.

**Comment by SEJeff** [comment]
Patches accepted :)

**Comment by kyzh** [comment]
What do you think of the following:
[logo](http://imgh.us/Whisper_-_Logo.svg)
[with font](http://imgh.us/Whisper_-_With_Font.svg)

Licence is CC-BY
Author is Nathan Rowe-Foster

**Comment by deniszh** [comment]
@kyzh @SEJeff - do we still want a logo?

**Comment by SEJeff** [comment]
It would be nice but on the list of priorities should be -1 unless someone contributes it.

**Comment by kyzh** [comment]
I'm not too sure what a pull request should look like to have the logo included.
The logo linked in my previous update are still available.
I'm personally not using graphite anymore, therefor I won't be doing the advocating for a logo much more
