### ISSUE TITLE
Enforce closing of files in 0.9.x

### ISSUE THREAD

**Issue by jjneely** [graphite-project/whisper#129]
I had a recurring problem where my `carbon-cache.py` writer thread would deadlock which I traced down to a race condition in `whisper.py`.  I had enabled Flock locking.  When an error occurred updating the WSP file (like a zero length file which generated the CorruptWhisperFile exception) the WSP file would not be closed.  A race condition between the Python GC (which would close the file referenced by an out of scope variable) and the next time there were data points to write to the same corrupt WSP file triggered a deadlock.  As the out of scope file descriptor wasn't closed the file was still locked and the writer thread would wait forever trying to obtain an exclusive lock on the same file.

This should easily be fixed by enforcing that files get closed.  I found that the master branch does this  but not 0.9.x.  I would offer a pull request but I much perfer the current method of using Python's with statement to the original commit's try/except/finally:

   f610a6505a76df4f4dca9099c0d9c6824b80cb57

That commit has been cleaned up several times since making it difficult to back port.

Is anyone up for a backport of this?  Or should I make a pull request with the original patch?

Is the master branch stable enough to run in production with a 0.9.12 / 0.9.13 Graphite setup?

**Comment by SEJeff** [comment]
You rock good sir! If you're ever in Chicago, find me for free :beers:
