### ISSUE TITLE
Whisper queries on existing files broken after upgrade from 0.9.10 to 0.9.14

### ISSUE THREAD

**Issue by dbeckham** [graphite-project/whisper#144]
I have a really odd whisper problem after upgrading to 0.9.14 from 0.9.10.  I can no longer see any data for a range that is less than 24 hours and is before the current day. I can see data for the current day, and I can see data for something like "the last week" at one time, but if I try to look at a single day in during that last week or whatever time period, no data points are returned. 

For example:

On my 0.9.14 installation, this whisper-fetch.py query for data from `Mon Nov 16 17:39:35 UTC 2015` until now returns what I would expect. All timestamps return data. `whisper-fetch.py --pretty --from=1447695575 myfile.wsp`.

However, this query for an hours worth of data starting at the previous time stamp returns `None` for all values. `whisper-fetch.py --pretty --from=1447695575 --until=1447699175 myfile.wsp`.

I thought I had seriously broken something with the installation, so I copied one of the whisper files back to the old server with 0.9.10 on it and ran the same whisper-fetch.py test queries an the same exact whisper files from the new server, and data shows up as I would expect.

My first thought was that somehow, somewhere I had screwed up retention, but the retention on these files haven’t changed in several years and it was working and continues to work 100% correctly on the old graphite server, even with whisper files copied back from the 0.9.14 server. 

This is the retention information from the specific file that I've been testing with:

```
# From whisper-info.py:
maxRetention: 315360000
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 5247424

Archive 0
retention: 86400
secondsPerPoint: 10
points: 8640
size: 103680
offset: 64

Archive 1
retention: 2592000
secondsPerPoint: 60
points: 43200
size: 518400
offset: 103744

Archive 2
retention: 63072000
secondsPerPoint: 300
points: 210240
size: 2522880
offset: 622144

Archive 3
retention: 315360000
secondsPerPoint: 1800
points: 175200
size: 2102400
offset: 3145024
```

**Comment by dbeckham** [comment]
I forgot to mention one other thing, the issues seems to occur between data resolutions. If I'm looking at month like September 1st to September 30th, it's empty, but August 31st to September 30th shows data.

**Comment by deniszh** [comment]
Maybe you can put your whisper file somewhere to check? IMO it'll help a lot with debugging this, because I never hard of similar problem before...

**Comment by dbeckham** [comment]
Sure. This is a stat that is updated every 10s and a newer version of the one I tested on: https://www.dropbox.com/s/xeptwxaoyc6roeb/test.wsp?dl=0

**Comment by xneo64** [comment]
I'm having what I suspect is the same problem. This is being manifested in graphs when I zoom in on historical data.

My wsp retentions are as follows:
`retentions = 10s:2h,2m:1d,1h:30d,6h:140d`

```
Meta data:
  aggregation method: average
  max retention: 12096000
  xFilesFactor: 0.5

Archive 0 info:
  offset: 64
  seconds per point: 60
  points: 120
  retention: 7200
  size: 1440

Archive 1 info:
  offset: 1504
  seconds per point: 120
  points: 720
  retention: 86400
  size: 8640

Archive 2 info:
  offset: 10144
  seconds per point: 3600
  points: 720
  retention: 2592000
  size: 8640

Archive 3 info:
  offset: 18784
  seconds per point: 21600
  points: 560
  retention: 12096000
  size: 6720
```

If I query for data from=3d ago until=2d ago (should fall in `1h:30d` archive) I should be receiving ~24 points - 1 hour spacing between each metric. But instead I'm receiving a bigger list of 'null' valued metrics with timestamps spaced 2 minutes apart. 

If I increase the query end time by any minimal value, then I do get the metrics.
I can replicate this consistently:

`10s:2h`
`2m:1d` <- query for 2hours or less - get null values // query 2hours+ get good values
`1h:30d` <- query for 1day or less - get null values // query 1day+ get good values

There seems to be a relationship between the queried interval and the max retention period of the previous archive.. This behavior is observed when using both the webapp and whisper-fetch.py.

**Comment by dbeckham** [comment]
@deniszh Both the retention periods from @xneo64 and my retention periods share one commonality. We have 2+ archives and they extend to over a year. Are our retention periods just out of the norm as far as testing usually goes? Graphite defaults are 90d for carbon stats and 1d for other metrics, and I often see people online using <1y retention periods, etc. Are regression tests done on large metric retention periods?

**Comment by dbeckham** [comment]
@deniszh  I was just able to confirm that this was working correctly in the 0.9.12 tag, but broken in the 0.9.x branch (and 0.9.14 tag) as well as the master branch.

Rough steps that I used to reproduce:

- `git clone https://github.com/graphite-project/whisper`
- Copy the `test.wsp` file from the dropbox link to the working dir
- In each branch/tag (master, 0.9.12 and 0.9.14):
```
git checkout <branch>
rm -rf build
python setup.py build
cp ./build/lib/*.py ./build/scripts-2.7/
cd ./build/scripts-2.7/
# A fetch from start until 'now' shows valid data in all tested branch and tags
./whisper-fetch.py --pretty --from=1447695575 ../../test.wsp
# A fetch for one hours worth of data from the same start date shows valid data
# in tag 0.9.12, but shows 'None' for all data points in master and tag 0.9.14
./whisper-fetch.py --pretty --from=1447695575 --until=1447699175 ../../test.wsp
```

**Comment by deniszh** [comment]
Sorry, I'm fully packed with working and personal stuff now, will try to properly dig into your file on weekend, not earlier. :( 
Maybe other contributors also can help...

**Comment by dbeckham** [comment]
@deniszh sorry for bothering you so much about this.

@obfuscurity This is the change that broke whisper fetching datapoints across precision boundaries: 5725d4dc061cd9ea40c1a6371f48d5bc762d6e9a

The same tests above work before that change, but not after.

**Comment by deniszh** [comment]
@dbeckham: No worries, no bothering - just give you some ETA. :)

**Comment by obfuscurity** [comment]
@dbeckham I suspected that was the change, but I'm really curious why that would cause this condition. I'll try to look at this over the weekend. We might have to ship a 0.9.15 after all. :frowning:

**Comment by elratt0r** [comment]
Please try this patch attached and say if it helps. It does for me but i am still investigating, why it helps ;-)

[whisper_fetch_patch.txt](https://github.com/graphite-project/whisper/files/39935/whisper_fetch_patch.txt)

**Comment by dbeckham** [comment]
@elratt0r this patch looks like a reverse of 5725d4d, which I definitely confirmed is causing the issue to manifest itself. I'm actually already running 0.9.14 in production with 5725d4d removed.  (i.e. your `whisper_fetch_patch.txt` patch applied.)

**Comment by obfuscurity** [comment]
Yes, I think we all agree that change needs to be reversed (and it will).

**Comment by obfuscurity** [comment]
Sorry for the breakage folks, but thanks to @dbeckham for reporting this bug and @elratt0r for explaining the behavior.

**Comment by mkrb** [comment]
I tested 0.10 and the problem seems to exist there, too (and in graphite-api in _vendor/whisper.py)
