### ISSUE TITLE
Suggested backup strategy

### ISSUE THREAD

**Issue by jareware** [graphite-project/whisper#148]
Hi,

I'm having a hard time finding info on a recommended way to back up whisper files.

There's projects like https://github.com/jjneely/whisper-backup that do lots of other things as well, but is there any simpler method? How likely am I to end up with corrupted whisper files if I simply `cp` the whole thing?

Thanks!

**Comment by deniszh** [comment]
whisper-backup using same lock files as whisper for making files consistent - https://github.com/jjneely/whisper-backup/blob/master/whisperbackup/whisperbackup.py#L169-L188
You can use snippet above to make own simpler backup script.
