### ISSUE TITLE
Enabling and improving whisper file header caching

### ISSUE THREAD

**Issue by pu239ppy** [graphite-project/whisper#158]
Currently this setting is not exposed through carbon, I have created a few branches that
1. Expose this setting through carbon-cache options
2. Creates a notion of entry which encapsulates a time stamp in addition to info
3. Allows carbon cache to control the ageing 

I do not expect my first proposal to be accepted but would like to start this conversation as caching would be very useful in order to decrease the number of disk iops

To this end I am proposing 
https://github.com/graphite-project/whisper/pull/157
https://github.com/graphite-project/carbon/pull/523
for your consideration

**Comment by deniszh** [comment]
Hi @pu239ppy !
It will be really great if you able to describe your change in couple of words - what's are you trying to solve and how?

**Comment by pu239ppy** [comment]
In short I am trying to reduce the number of io ops carbon-cache imposes on
the disk.  One way to do this is decrease updates per second, but caching
the wsp file header is great as well since we now do not have to perform
reads for every write.  I was going to implement it myself, but noticed
that it is already there.  My changes allow admins to enable header caching
through a carbon [cache] setting, and also add time stamps (whisper code)
and ageing operations to (carbon code) carbon.

**Comment by bmhatfield** [comment]
I commented on https://github.com/graphite-project/carbon/pull/523 without realizing there were multiple places this issue was filed. Please read that comment.

**Comment by pu239ppy** [comment]
Brian, I replied, but also including the reply here for visibility.

Brian, this setting is not mandatory, and in fact disabled by default.
While it would be possible to have a unified cache with a caching system I
am reluctant to add more components (caching layer such as redis) to
carbon.
