### ISSUE TITLE
Allow whisper to store data in a whisper file relative to the timestamp of the latest datapoint instead of current date

### ISSUE THREAD

**Issue by Styx13** [graphite-project/whisper#160]
Hello,

From my observation and a quick look at the code, it looks like whisper is storing data in the files relative to the current time.

I.E.: I create a new whisper file (empty) with the following retention : 1s:5m 10s:1d 1m:30d 5m:90d 15m:1y
If the current date is January 1st 2016 and for whatever reason I want to store a datapoint from august 15h 2015, this datapoint (and its timestamp) will be stored directly in the last archive (15m:1y)

I am wondering if it would be easy to modify whisper's behavior to the following:
for a given whisper file, as a new datapoint is added to the file:
 => check its timestamp
 ==> if it's timestamp is newer than any timestamp previously recorded, make this new timestamp the relative "starting date" of the file. (if this is the first datapoint added to the file, then make its timestamp be the "starting date")
And then use this "starting date" instead of the current time.

This way, if I take my previous example again, this time, when I add my datapoint from august 15th 2015, it will be stored in all archives, and august 15th 2015 will be considered as the "starting date" of this whisper file.
Then, if I add a new datapoint to that whisper file long after that date, let say on December 25th 2015, then December 25th 2015 becomes the new "starting date" and this new datapoint get stored in all archives, while my previous datapoint gets removed form all archives but the last.

If this makes sense, the idea behind that is to allow to store in whisper some old data but still at a high precision as long as there has been no new datapoint added.

Let's say I have stored somewhere (a cvs file for example) some datapoint from last year at a precision of 10 seconds and just for a duration of 4 hours.
If I wanted to import them to the whisper database, with the current behavior of whisper and with the retention setup indicated above, it would get stored with a 15 minutes precision (so I would lose my 10s precision).
With the modified behavior, it would actually store it with a 10s precision.

Anybody has an idea if this could be done easily ?

If I am not clear in my explanation, let me know and I will try to explain better.

**Comment by SEJeff** [comment]
Pretty sure the answer here is no and that it would require a backwards incompatible change to the whisper format

**Comment by Styx13** [comment]
This is probably true yes, but as I read in #86 , there might be plans to rewrite part of whisper to make it more efficient, I was thinking that maybe this "feature" could be added at the same time.

As I think about it, "starting date" would probably not be the right term, but something like "lastDatapointTimestamp" might make more sense, and then whisper could refer to this date instead of the current time.
I believe the rest of the whisper mechanics would be mostly same, just it would use this lastDatapointTimestamp date instead of current time, and every time a new datapoint is added: compare the datapoint timestamp to lastDatapointTimestamp and update lastDatapointTimestamp if the new datapoint timestamp is more recent.

The Header could be modified as follow:

```
  # File = Header,Data
  # Header = Magic, Version, Metadata,ArchiveInfo+
  #              Magic = "WHISPER"
  #              Version = Version information in ascii, 5 characters "01.00"
  #     Metadata = lastDatapointTimestamp, aggregationType,aggregationMetadataSize,   maxRetention,xFilesFactor,archiveCount,
  #     ArchiveInfo = Offset,SecondsPerPoint,Points
  # Data = Archive+
  #     Archive = Point+
  #         Point = timestamp,value, aggregationMetadata
```

**Comment by DanCech** [comment]
One thought I had on this topic was that on write it might be possible to use the timestamp in the baseInterval to calculate the offset for the time period then verify whether the point at that interval is already newer than the provided point, and if so then reject the update.  That isn't perfect but it seems like it would allow for writing data without being dependent on the "current" timestamp.

On read we already check whether each point read matches the expected timestamp, the big change required would be in the code that decides which archive should be used for a given query.  First it can check each archive's maxRetention against the query period to discard archives that couldn't cover the period (ignoring current time and just looking at request interval vs maxRetention), but then we'd have to scan each potential archive to figure out which one actually has enough the data for the period (and that could get tricky if the archive doesn't have data for every interval in the requested period).
