### ISSUE TITLE
whisper-fill.py work with directories?

### ISSUE THREAD

**Issue by castrojsec** [graphite-project/whisper#164]
what would be the syntax to fill whisper files under one directory?  also, can the source be on a different server?

**Comment by deniszh** [comment]
whisper-fill working only with local files. So, you need to properly script your source and destination using e.g. bash. If file is remote - you need to copy file locally.
Or maybe you need to check https://github.com/graphite-project/carbonate or https://github.com/jjneely/buckytools - maybe it's what you looking for.
