### ISSUE TITLE
clean up whisper files

### ISSUE THREAD

**Issue by toopa2002** [graphite-project/whisper#165]
I'm finding a tool to clean up un-modified  whisper files which older than than last retention period configured in storage-schemas.conf file.

For example: Machine A sent out many metrics and the last sent out message is more than 60 days ago. Given that configured retention period for this metrics is 
"retentions = 1s:15d, 10s:30d, 60s:60d".  In this situation I would find and remove all whisper files which have last modify date older than 60 and delete it.

Are there any tools to read all patterns and retention periods in storage-schemas.conf file and remove un-modified whisper file as my above example?

**Comment by deniszh** [comment]
Not sure why you need to check retentions here. You can safely rely on modification time of wsp file itself. So, something like `find /opt/graphite/storage/whisper -name '*.wsp' -mtime +60 -print` will give you list of files were not updated for last 60 days.
