### ISSUE TITLE
whisper-diff.py new input parameter (--until)

### ISSUE THREAD

**Issue by diuis** [graphite-project/whisper#182]
Hi all,
I'm using grafana, graphite, carbon and whisper, and I need a little enhancement on the whisper-diff python tool.
I'm using the tool to verify if the whisper files are synchronized on a cluster of up and running carbon machine.
Because we have many metrics per minutes we are using carbon cache, and, obviously, we have a lot of false positives for the very last metrics.
In my use case could be a great enhancement adding a new parameter (--until) to pass to the script the epoch time until I want the diff check.
I'm not a python developer, but I changed a little the whisper and the whisper-diff scripts.
I'd like to open a pull request for a code review.
What do you think about? Could be useful to integrate my improvement in the codebase?
Thank you very much!

**Comment by deniszh** [comment]
Sure, please submit a PR. Thanks a lot!

**Comment by diuis** [comment]
Thanks Denis,
my PR is there: https://github.com/graphite-project/whisper/pull/183

**Comment by deniszh** [comment]
Merged!
