### ISSUE TITLE
JSON output for whisper-diff.py

### ISSUE THREAD

**Issue by diuis** [graphite-project/whisper#184]
Hi all,
I'm working a lot with whisper-diff.py in my production environment, and I think that the same enhancement proposed for whisper-info.py script would be useful for the whisper-diff.py (https://github.com/graphite-project/whisper/issues/159): return a json output to manipulate it programatically.
If you think that this could be useful, I can open a PR.
I'm a python newbie: any suggestion is welcome!

**Comment by obfuscurity** [comment]
Sure.

**Comment by diuis** [comment]
Thanks @obfuscurity !
PR created: https://github.com/graphite-project/whisper/pull/186
I would like to open another PR, because I think that could be useful a little patch to the whisper.py script to skip, on the diff function, not only the empty values on both files, but also the points where one side (for example the path_a file has a null datapoint).
Let me know.

**Comment by diuis** [comment]
If the the code for the json output is ok, I can contribute also to the https://github.com/graphite-project/whisper/issues/159 issue.

**Comment by obfuscurity** [comment]
Fixed in #186.
