### ISSUE TITLE
whisper-resize - ValueError: too many values to unpack

### ISSUE THREAD

**Issue by d-zalewski** [graphite-project/whisper#189]
I'm trying to change  retentions = 1m:90d,5m:180d,30m:240d,360m:4y

`srv1:root:/var/lib/carbon/whisper> find ./ -type f -name '*.wsp' -exec whisper-resize --nobackup {} 1m:90d,5m:180d,30m:240d,360m:4y \;`

`Traceback (most recent call last):
  File "/usr/bin/whisper-resize", line 70, in <module>
    for retentionDef in args[1:]]
  File "/usr/lib/python2.6/site-packages/whisper.py", line 122, in parseRetentionDef
    (precision, points) = retentionDef.strip().split(':')
ValueError: too many values to unpack
`

**Comment by obfuscurity** [comment]
There's no comma delimiter between retentions, just use a single space.
https://github.com/graphite-project/whisper/blob/master/bin/whisper-resize.py#L23

```
 find ./ -type f -name '*.wsp' -exec whisper-resize --nobackup {} 1m:90d 5m:180d 30m:240d 360m:4y \;
```

**Comment by d-zalewski** [comment]
My bad! Thanks that did the trick
