### ISSUE TITLE
whisper-fill.py is not python3 compatible in feature/py3 branch

### ISSUE THREAD

**Issue by yunstanford** [graphite-project/whisper#190]
https://github.com/zillow/whisper/blob/feature/py3/bin/whisper-fill.py#L75

such as,
itertools.izip, itertools.izip, xrange etc.

it can be an easy fix.

**Comment by deniszh** [comment]
Yes, any parts of Graphite stack currently are not python3 compatible. But the whisper is also a library, so it makes sense, though. So, patches are welcome! Of course, we should maintain compatibility with python 2.x too.

**Comment by piotr1212** [comment]
This is implemented
