### ISSUE TITLE
Attempting to fix incorrectly aggregated data

### ISSUE THREAD

**Issue by aidos** [graphite-project/whisper#191]
I have a couple of metrics that were incorrectly named leading them to be picked up by the rule with `aggregationMethod = sum` instead of `aggregationMethod = average`. The retention is `20s:1d,1m:7d,10m:1y`.

It's a bit of a long shot, but it seems that, since I know the breakdown of the retention periods and everything has been aggregated by summing, it should be possible to "fix" the data to more or less swap the sum for an average by dividing by the number of points in each retention period.

In particular, in my case, I only have one data point every minute for the first 2 retention periods so I think I should be able to take the final archive (`10m:1y`) and divide it all by 10.

Has anyone been through this?

**Comment by deniszh** [comment]
Maybe it's possible, but it'll definitely require writing of custom migrator code.
