### ISSUE TITLE
Upgrading from 0.9.13 can delete all wisper db's.

### ISSUE THREAD

**Issue by JasperWallace** [graphite-project/whisper#192]
I'm not sure how i managed this but the sequence looks like:

1. backup the sqlite db as described in the docs
2. backup the local_settings.py because why not.
3. export PYTHONPATH="/opt/graphite/lib/:/opt/graphite/webapp/" 
4.  pip install https://github.com/graphite-project/whisper/tarball/master
 - whisper 0.10.0rc1 is successfully installed
5. realise i should probably stop apache and the carbon cache before upgrading things
6. /opt/graphite/bin/carbon-cache.py stop
7. /etc/init.d/apache2 stop
8. pip install https://github.com/graphite-project/carbon/tarball/master
 - 0.9.13 is uninstalled and 0.10.0rc1 installed
9. pip install https://github.com/graphite-project/graphite-web/tarball/master
 - setup tools barfs on cffi and not being able to find setuptools_ext
10. install python-setuptools from jessie-backports, i get 20.10.1-1.1~bpo8+1
11. i realise that the master branch is getting me 0.10.0rc1, I'd prefer to not have a release candidate and am not sure how well 0.10.0rc1 will play with my grafana install so decide to downgrade to 0.9.15
12. pip install https://github.com/graphite-project/whisper/archive/0.9.15.tar.gz
13. pip install https://github.com/graphite-project/carbon/archive/0.9.15.tar.gz
14. pip install https://github.com/graphite-project/graphite-web/archive/0.9.15.tar.gz
 - ll the above proced with no errors, 0.10.0rc1 is uninstalled in every case
15. I run syncdb and migrate, both say "No migrations to apply."
16. apache gives 500 errors, some poking around shows that graphite now wants to write to some more log files in /opt/graphite/storage/log/webapp/, chown'ing the directory to www-data:www-data fixes that.
17. at this point i try to see some graphs, but they all show 'no data'. Some pokeing around shows that '/opt/graphite/storage/whisper' is bare, it slowly fills up with new .wsp files as metrics come in 😿

**Comment by deniszh** [comment]
Hi @JasperWallace ,
Ooh, sorry for your loss! That's really strange behavior, never heard of anything similar. I'll try to reproduce that in VM.

**Comment by JasperWallace** [comment]
fwiw, the previous version of setuptools was 5.5.1-1 (stock debian jessie).

**Comment by deniszh** [comment]
Which version of pip do you using?

**Comment by JasperWallace** [comment]
`
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
`
Which is from the debian python-pip package version 1.5.6-5
