### ISSUE TITLE
Questions about whisper

### ISSUE THREAD

**Issue by shivagopalan** [graphite-project/whisper#194]
Hi, I am working on setting up a benchmarking project for monitoring workflows. I have decided to use Graphite for the most part, but in some situations we may be bypassing carbon, so I am evaluating whisper as a standalone tool. I looked through the whisper code and have some questions about it.

1. Where do you configure the header to be passed into whisper? I intend to tag the metrics with process id in the header. 
2. Can I query whisper with header as a parameter?
3. In cluster mode, Should whisper be local to master node or can it run on any node? 
4. Does carbon invoke WhisperDatabase? I looked through the code , but was unable to locate that. 

I would highly appreciate it if you can point me in the right direction here.

**Comment by deniszh** [comment]
1. Now header format is hardcoded - https://github.com/graphite-project/whisper/blob/78f761c8377c4ec64be1ab62333eb8f9b46a8c53/whisper.py#L108
And whisper have no version field in header, so, you can create own whisper format, but it will be not compatible with existing tools.
2. Not really understand what you mean. Probably no.
3. Whisper is local database, it has no "cluster mode".
4. Yes, it's initializing `state` object with `database` instance, which is currently `WhisperDatabase` or `CeresDatabase`

**Comment by jssjr** [comment]
> Where do you configure the header to be passed into whisper? I intend to tag the metrics with process id in the header.

> Now header format is hardcoded - https://github.com/graphite-project/whisper/blob/78f761c8377c4ec64be1ab62333eb8f9b46a8c53/whisper.py#L108
And whisper have no version field in header, so, you can create own whisper format, but it will be not compatible with existing tools.

I believe it should be possible to extend the whisper format without breaking backwards compatibility as long as you don't modify how datapoints are stored in the archive. I've outlined by theory in https://github.com/graphite-project/whisper/issues/86#issuecomment-84718927 and intended to use that strategy for another project, but it never came to fruition.

**Comment by shivagopalan** [comment]
Thank you for your response.
