### ISSUE TITLE
whisper out of range time range cause incorrect value to be returned

### ISSUE THREAD

**Issue by mleinart** [graphite-project/whisper#21]
#### Imported from https://bugs.launchpad.net/bugs/1111285

|  |  |
| --- | --- |
| Reported by | [sbernard](https://launchpad.net/~sbernard) |
| Date Created | Jan 31, 2013 |
| Tags | [] |

 When specifying a range in the future, fetch_file accepts the range as ok and returns an incorrect timeinfo with an end < start.

How to reproduce :
take any timeseries
Call fetch_file with 
   from = now + 1h
   until = now + 3h

fetch_file returns a series of NONE values correct with a timeinfo like this:

  start = from
  end  = now

As from is in the future, the timeinfo returned has end < start which is cleary a bug.

**Comment by deniszh** [comment]
Looks like non-reproducible anymore...
