### ISSUE TITLE
Testing on windows// Error:  "AttributeError: 'module' object has no attribute 'uname'"

### ISSUE THREAD

**Issue by seanvree** [graphite-project/whisper#212]
Platform:  Windows 10E
Python 27

Trying to get Whisper working on windows. I know this isn't "designed" for windows, but there's no reason it shouldn't work with proper PATHs set. 

So, I can run the installer fine:

```
C:\whisper>python setup.py install
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
running install_egg_info
Removing C:\Python27\Lib\site-packages\whisper-1.1.0-py2.7.egg-info
Writing C:\Python27\Lib\site-packages\whisper-1.1.0-py2.7.egg-info
```

However, when I try to run the test I get the following:

```
C:\whisper>python test_whisper.py
Traceback (most recent call last):
  File "test_whisper.py", line 27, in <module>
    import whisper
  File "C:\whisper\whisper.py", line 69, in <module>
    if os.uname()[0] == 'FreeBSD':
AttributeError: 'module' object has no attribute 'uname'

```

Cause:  Windows doesn't recognize "IMPORT OS", 

Ref:
http://bugs.python.org/issue8080

so I removed IMPORT OS from the setup.py and test_whipser.py files to  IMPORT PLATFORM and reinstalled the package, but I can't get past this error. 

Any ideas?

**Comment by seanvree** [comment]
wow, totally reported this error in the wrong REPO!  DERP!

**Comment by deniszh** [comment]
Yes, Graphite on Windows is totally not-supported.  Not even sure if it will work at all. Patches are welcome. :)

**Comment by seanvree** [comment]
@deniszh  - I got that, but I KNOW it works. I've seen it, I've worked on it.  For some reason, in my environment, I can't get past this minor error.

**Comment by deniszh** [comment]
NP, if you able to run Graphite on Windows - we'll glad to add Windows to the list of supported platforms. Unfortunately, I have no Windows to test.

**Comment by seanvree** [comment]
@deniszh  - Well, I know it DOES work, but I can't get it to work on my machine, that's why I was asking for help.

**Comment by deniszh** [comment]
Sure, just mentioned that Graphite maintainers, unfortunately, will not able to help, at least for now. (maybe I can try to test it on some trial VM, but have no time for that now). 
But maybe somebody else will.

**Comment by piotr1212** [comment]
I think you forgot to change os.uname to platform.uname on line 69 in whisper.py

**Comment by piotr1212** [comment]
A bit late but this should fix your issue https://github.com/graphite-project/whisper/pull/262 . (Well I think as I don't have a Windows copy around)
