### ISSUE TITLE
Problem with the metric hostalive/RTA on Icinga

### ISSUE THREAD

**Issue by sballaud** [graphite-project/whisper#220]
Hello,

I have an issue with the whisper files in ../carbon/whisper/icinga2/HOSTNAME/host/hostalive/perfdata/rta/value.wsp. Unlike the others metrics (for example CPU System), RTA metric doesn't display the value in the correct order. For example, an extract of the whisper file for CPU System metric :

Archive 0 info:
offset: 52
seconds per point: 60
points: 2880
retention: 172800
size: 34560

....
Archive 0 data:
0: 1496243760, 68
1: 1496243820, 65
2: 1496243880, 65
3: 1496243940, 60
4: 1496244000, 60
5: 1496244060, 62
6: 1496244120, 68
7: 1496244180, 65
8: 1496244240, 66
9: 1496244300, 65

As we can see, the difference between 2 metrics is 60 seconds. But for the RTA metric, it's different :

Archive 0 info:
offset: 52
seconds per point: 60
points: 2880
retention: 172800
size: 34560
....
Archive 0 data:
0: 1496158020, 0.00063000000000000002612493554821071484
1: 1496330880, 0.00058100000000000002770700335830156291
2: 1496158140, 0.00046500000000000002702699175571865453
3: 1496331000, 0.00039899999999999999486174906415669739
4: 1496158260, 0.00051300000000000000113797860024078545
5: 1496331120, 0.00053899999999999998259725408900067123
6: 1496158380, 0.0011930000000000000499877916837476732
7: 1496331240, 0.00042600000000000000062796989830360417
8: 1496158500, 0.00074100000000000001369043767240896159
9: 1496331360, 0.00052099999999999997875310686623606671

As we can see on the metric 0 and 1, the difference is not 60 seconds but 172860 seconds (retention period + seconds per point). But the different between the metric 0 and 2 is good because it's 60 x 2.

If someone could explain me why. It's the same issue on all the servers. But when i display the graphic on the Web interface, it's OK.

Thanks !

**Comment by deniszh** [comment]
Whisper archives are cyclic - when it comes to the end it will start to overwrite first values. That's perfectly fine.
