### ISSUE TITLE
Provide a method to select granularity

### ISSUE THREAD

**Issue by adriangalera** [graphite-project/whisper#225]
Hi! 
Whisper fulfills our use cases at 99%, the only thing we miss is the ability to select the archive to extract the data in the files.

Looking at the code, it seems (fetch) that always get the file with the lowest granularity possible.

Would it be possible to add another method to be able to select the granularity?

**Comment by deniszh** [comment]
Usually, it's what user wants - lowest granularity, most precise data. You can use `__archive_fetch(fh, archive, fromTime, untilTime)` to fetch data from the particular archive, but it's a bit tricky. We can introduce optional parameter, e.g. archive_number, which will give you the ability to get data from a specific archive (0, 1, 2...).
Does it looks like an acceptable solution for you?

**Comment by adriangalera** [comment]
Currently I am developing a workaround to select the archive based on the points per second defined in the file. As soon as I have finished, I will make a PR

**Comment by deniszh** [comment]
To be clear - that functionality was implemented and was released in whisper 1.0.2
