### ISSUE TITLE
Store data every millisecond

### ISSUE THREAD

**Issue by rp-happiestbaby** [graphite-project/whisper#229]
Hi,
Im trying to store data every 5 ms 1 datapoint i tried to edit config file and set following but I get an error.
So what is wrong?  Milliseconds are not supported ? 
/opt/graphite/conf/storage-schemas.conf
[default_1ms_for_30day]
pattern = .*
retentions = 1ms:30d

**Comment by deniszh** [comment]
Yes, minimal resolution for whisper is 1 second, I just found out that documentation didn't mention that.
