### ISSUE TITLE
Unknown distribution option: 'install_requires error: no commands supplied

### ISSUE THREAD

**Issue by guilhermeaugustos** [graphite-project/whisper#232]
Hi therere,

When I try to run the setup.py script i receive that error message:

>  /home/guilherme/anaconda2/lib/python2.7/distutils/dist.py:267:
> 
>  UserWarning: Unknown distribution option: 'install_requires'
>   warnings.warn(msg)
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: no commands supplied

I search something about that, and the recomendation is substitute the distutils.core for setuptools , so the warning message disapper but the error persist. I totally a begginer in python and datasources so excuse-me my question in that.

**Comment by deniszh** [comment]
It's a warning, it should not interrupt your install. 
Could you please give a full command which you trying to run?

BTW, you can use [Synthesize](http://graphiteapp.org/quick-start-guides/synthesize.html) or [Docker](https://graphite.readthedocs.io/en/latest/install.html#docker) for easier installation of Graphite.

**Comment by guilhermeaugustos** [comment]
@deniszh I just run 

/home/guilherme$python setup.py

I tried in this way cause i just follow the [this](https://github.com/esnet/esmond/tree/develop/util/graphite) instruction. In my case, I tried to use the "And ESnet local changes" branch find [here](https://github.com/esnet/graphite-web/tree/esnet_tweaks) .

About the docker installation i have tried, but  i tried the docker installation with the graphite-api, and I make some mistakes and the installation wasn't work and left some trash. So my graphite-web docker installation failed cause there some process running. I remove all my graphite-api containers and tryind to install the graphite-web docker install again righ now.

**Comment by guilhermeaugustos** [comment]
I tried the docker graphite-web instalation again and receive that error: 

>  Status: Downloaded newer image for graphiteapp/graphite-statsd:latest
> 8007167d844c070dbbabcca7d6e70e754280f9b60a4eaa41090af9f6ef998b39
> docker: Error response from daemon: driver failed programming external connectivity on endpoint graphite (122e149b2008aca6da17cf52da2144d6ccfd27fb9b249690158bc7f9c939df0c): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use

**Comment by deniszh** [comment]
>I just run
>
>/home/guilherme$python setup.py

Indeed. And you need to provide command for setup.py - when you providing nothing, nothing happens.

>I tried in this way cause i just follow the this instruction. In my case, I tried to use the "And ESnet local changes" branch find here .

I can be wrong but looks like this stuff is 5 years old, at least. You can give it a try, of course - but then you need to run proper command: `python setup.py install`

> Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use

Port 80 is already occupied on your machine. Try to change it to something else, e.g. 8080:
```docker run -d\
 --name graphite\
 --restart=always\
 -p 80:8080\
 -p 2003-2004:2003-2004\
 -p 2023-2024:2023-2024\
 -p 8125:8125/udp\
 -p 8126:8126\
 graphiteapp/graphite-statsd```

**Comment by guilhermeaugustos** [comment]
Ok, i'm really stupid. Didn't notice that I nedd the install argumment. I wanna use [that](https://github.com/esnet/esmond/tree/develop/util/graphite) stuff cause I need to graph in a grafana plugin the timeseries data from [here](http://monipe-maesmond.rnp.br/). The [documentation](http://software.es.net/esmond/index.html) says I can use graphite to show these datas, and grafana supports graphite. So, for thtat purpose I  was trying to use [that](https://github.com/esnet/esmond/tree/develop/util/graphite). I saw two options, make that esmond graphite integration work and use graphite to source datas to my grafana plugin, or query datas from  [here](http://software.es.net/esmond/index.html) using the [perfSONAR Python Client Libraries](http://software.es.net/esmond/perfsonar_client_python.html) and then structure the datas in the Simple JSON [format](http://docs.grafana.org/plugins/developing/datasources/) accepts in grafana
