### ISSUE TITLE
Whisper on s3?

### ISSUE THREAD

**Issue by adriangalera** [graphite-project/whisper#233]
Hi! Currently we're thinking on migrating our current implementation using whisper to a serverless infrastructure.
I am wondering if we would be able to use whisper using the amazon s3 for instance, in order to do so, we would need to pass a file descriptor instead of the file path.
Do you think it will be possible to do that?
Thanks

**Comment by DanCech** [comment]
The libary exposes most whisper functionality as paired functions that accept a path and a file handle.  See `update()` and `file_update()` for example.
