### ISSUE TITLE
Aggregation policy is not working

### ISSUE THREAD

**Issue by rp-happiestbaby** [graphite-project/whisper#234]
Hi,
Im running graphite/whisper 

Aggregation policy is : 20s:7d,60s:30d,30m:1y,1d:5y

My worker which one produce data runes every 20sec~5min (but it usually once in 5 min or twice but it can run more times )

So I can see data for last 7 days,
But When i'm selecting last 8 days there are no data.

It looks like aggregation is Not woking or there are a lot of null values and AVG for 60 sec is null? 

Please help on this.

**Comment by piotr1212** [comment]
whisper is a fixed interval timeseries database. If too much values are missing it doesn't aggregate to the next retention schema. The amount of needed datapoints is configurable with the xFilesFactor setting in storage-aggregation.conf. If your worker cannot send metrics in with a fixed interval you most likely want to use an aggregator, for example carbon-aggregator, carbon-c-relay with aggregation, or statsd.
