### ISSUE TITLE
Document "week" / "w" as an allowed unit

### ISSUE THREAD

**Issue by mcv21** [graphite-project/whisper#239]
Hi,

The current documentation - http://graphite.readthedocs.io/en/latest/config-carbon.html#storage-schemas-conf lists second/minute/hour/day/year as the possible time units; but week is also in use (e.g. the O'Reilly Graphite book uses it), and the code supports it. Could this be added to the documentation, please?

Thanks :)

**Comment by deniszh** [comment]
Hello @mcv21,
Sure! Even better - you can add it too if you want. 
Sources for documentation from https://graphite.readthedocs.io/ is in graphite-web repo - https://github.com/graphite-project/graphite-web/tree/master/docs - any user can fork repo, edirt docs and send PR.
Not saying that you should do that, of course, just a reminder.
Thanks for reporting! 👍

**Comment by mcv21** [comment]
I think that PR should do the trick...

**Comment by deniszh** [comment]
Merged! Thanks
