### ISSUE TITLE
whisper-auto-resize fails if metric file contains $

### ISSUE THREAD

**Issue by eserte** [graphite-project/whisper#240]
If a metric file to be resized contains a `$` then whisper-auto-resize fails:
```
# sudo -u _graphite whisper-auto-resize.py -x --nobackup --subdir /var/lib/graphite/whisper/... /var/lib/graphite/whisper /etc/carbon --doit

updating Retentions from: 60:240 300:432 600:5040 3600:2160 7200:4380 86400:3650  to: 60:1440 300:2016  

/usr/bin/whisper-resize "/var/lib/graphite/whisper/.../cache/LocalCache$LocalLoadingCache/startpagemobile/cache/size.wsp" --nobackup --xFilesFactor=0.5 --aggregationMethod=average 60:1440 300:2016 
[ERROR] File '/var/lib/graphite/whisper/.../cache/LocalCache/startpagemobile/cache/size.wsp' does not exist!
```

Obviously it looks like `$LocalLoadingCache` was interpreted as a (non-existent) shell variable and this part simply vanished in the `whisper-resize` call.

Looking at the code it seems to me that the `cmd` should not be created as a string, but as an array, and `call` should use this array and set `shell=False`. And the `print cmd` probably needs some adjustment.

**Comment by piotr1212** [comment]
The fix is merged? Can this be closed?

**Comment by eserte** [comment]
It seems so.
