### ISSUE TITLE
whisper module could not be loaded

### ISSUE THREAD

**Issue by YouriAndropov** [graphite-project/whisper#243]
Hi, I'm installing graphite and apache in user mode and I do have some problems.

When I start apache, I get the following log in graphite webapp log :
```
[Tue Jan 02 01:02:41.718859 2018] [wsgi:error] [pid 15318:tid 140524069676928] WARNING: whisper module could not be loaded, whisper support disabled
[Tue Jan 02 01:02:41.720538 2018] [wsgi:error] [pid 15322:tid 140524069676928] WARNING: whisper module could not be loaded, whisper support disabled
[Tue Jan 02 01:02:41.730025 2018] [wsgi:error] [pid 15320:tid 140524069676928] WARNING: whisper module could not be loaded, whisper support disabled
[Tue Jan 02 01:02:41.747643 2018] [wsgi:error] [pid 15319:tid 140524069676928] WARNING: whisper module could not be loaded, whisper support disabled
[Tue Jan 02 01:02:41.752027 2018] [wsgi:error] [pid 15321:tid 140524069676928] WARNING: whisper module could not be loaded, whisper support disabled
```
No problem in apache error_log :
```
[Tue Jan 02 01:02:40.960276 2018] [mpm_event:notice] [pid 15317:tid 140524069676928] AH00489: Apache/2.4.29 (Unix) mod_wsgi/4.5.24 Python/2.7 configured -- resuming normal operations
[Tue Jan 02 01:02:40.960374 2018] [core:notice] [pid 15317:tid 140524069676928] AH00094: Command line: '/opt/httpd/bin/httpd'
```

Whisper was installed from sources with --prefix=/opt/graphite. So all whisper python files are in /opt/graphite/bin. But apache doesn't seem to find them.

How can I solve this ?

**Comment by deniszh** [comment]
This issue should be opened for graphite-web, not whisper. But OK.
Usually, wsgi script appends graphite installation path to sys.path - e.g. https://github.com/graphite-project/graphite-web/blob/master/conf/graphite.wsgi.example
Check your wsgi script.

**Comment by YouriAndropov** [comment]
Ok, but I don't understand why some python modules are in $GRAPHITE_ROOT/lib/ (carbon+twisted) and some others are in $GRAPHITE_ROOT/lib/python2.7/site-package/ (whisper).

I solved the issue by pip installing whisper and some other missing dependencies, but now I don't know which package is used ($GRAPHITE_ROOT/lib/ or /usr/lib/python2.7/site-package/), and some permission error arise (carbon-cache log) :

```
02/01/2018 11:59:27 :: Unhandled error in Deferred:
02/01/2018 11:59:27 :: Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.

```

**Comment by deniszh** [comment]
>Ok, but I don't understand why some python modules are in $GRAPHITE_ROOT/lib/ (carbon+twisted) and some others are in $GRAPHITE_ROOT/lib/python2.7/site-package/ (whisper).

That's wrong. Whisper should be installed to $GRAPHITE_ROOT/lib/ too.

**Comment by YouriAndropov** [comment]
Ok you can consider this issue closed, I managed to run graphite with 'pip install'.
