### ISSUE TITLE
whisper-resize incorrect behaviour

### ISSUE THREAD

**Issue by fake-name** [graphite-project/whisper#244]
```

_graphite@graphical:/tank/carbon/whisper/statsite$ whisper-resize ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp 15s:10y 5m:10y 1h:10y
Retrieving all data from the archives
Creating new whisper database: ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp.tmp
Traceback (most recent call last):
  File "/usr/bin/whisper-resize", line 103, in <module>
    whisper.create(newfile, new_archives, xFilesFactor=xff, aggregationMethod=aggregationMethod)
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 356, in create
    validateArchiveList(archiveList)
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 330, in validateArchiveList
    (i, retention, i + 1, nextRetention))
whisper.InvalidConfiguration: Lower precision archives must cover larger time intervals than higher precision archives (archive0: 315360000 seconds, archive1: 315360000 seconds)

```

In this case, I'm only creating the lower-bin values because I want to have them precalculated for faster loading via grafana. 

(Note: I'm not sure this is a correct assumption)

After migrating:

```
_graphite@graphical:/tank/carbon/whisper/statsite$ whisper-resize ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp 15s:10y 5m:15y 1h:20y
Retrieving all data from the archives
Creating new whisper database: ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp.tmp
Created: ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp.tmp (273312052 bytes)
Migrating data without aggregation...
Renaming old database to: ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp.bak
Renaming new database to: ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp
_graphite@graphical:/tank/carbon/whisper/statsite$ whisper-resize ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp 15s:10y 5m:15y 1h:20y
Retrieving all data from the archives
Creating new whisper database: ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp.tmp
Created: ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp.tmp (273312052 bytes)
Migrating data without aggregation...
Renaming old database to: ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp.bak
Renaming new database to: ./timers/ReadableWebProxy/VpsHerder/VM-Creation/stdev.wsp
_graphite@graphical:/tank/carbon/whisper/statsite$

```

So. Apparently whisper-resize both does not check if the migration target matches the file already, and it will blindly clobber any `<database>.wsp.bak` file if it's present. 

The former is just annoying, the fact that if you re-run a conversion, it will clobber the backups is a major issue.

**Comment by deniszh** [comment]
>In this case, I'm only creating the lower-bin values because I want to have them precalculated for faster loading via grafana.
(Note: I'm not sure this is a correct assumption)

I think it's not. If you already have 15s resolution data for 10 years - why do you need to keep lower resolution data for the same period?

>So. Apparently whisper-resize both does not check if the migration target matches the file already, and it will blindly clobber any <database>.wsp.bak file if it's present.

Yes, currently it's trust user in any actions. And as I see `--force` does nothing in the current code.

**Comment by fake-name** [comment]
> I think it's not. If you already have 15s resolution data for 10 years - why do you need to keep lower resolution data for the same period?

Mostly because I'm making some (guesswork-based) assumptions about how things work. With 15s/10y data, to display 1d/10y data, it needs to read the entire file, and bin it down on the fly.

If you keep precalculated lower bins, I'd hope whisper would use the binned data. 

If I have a dashboard with a LOT of metrics, right now it takes quite a while to load.

**Comment by deniszh** [comment]
> Mostly because I'm making some (guesswork-based) assumptions about how things work. With 15s/10y data, to display 1d/10y data, it needs to read the entire file, and bin it down on the fly.

That's not how Graphite/Whisper works. IIRC it will pick lowest resolution anyway - https://github.com/graphite-project/whisper/blob/master/whisper.py#L929-L936
i.e. it will always pick up 15s:10y.

**Comment by fake-name** [comment]
> That's not how Graphite/Whisper works. IIRC it will pick lowest resolution anyway - https://github.com/graphite-project/whisper/blob/master/whisper.py#L929-L936
i.e. it will always pick up 15s:10y.

That... is kind of grossly suboptimal.

Is there any reason that this particular optimization couldn't be done? If you have a lower-resolution dataset, why not use it for faster loads?

**Comment by DanCech** [comment]
Because whisper doesn't know what you're going to do with the data, and there are plenty of situations where choosing lower-resolution data will cause problems.  If you want to be able to control the resolution used you can create 2 whisper files with different retention settings and specify the one you want at query time.

**Comment by fake-name** [comment]
Oh, apparently I'm *really* a derp, and I assumed the querying process included which time-resolution you wanted.
