### ISSUE TITLE
Data storage question

### ISSUE THREAD

**Issue by korish** [graphite-project/whisper#247]
As I see, whisper stores data in fix-sized .wsp files. I've read about it but still have some questions to clarify:

1. I've tried to save metrics 1 item per second into whisper for about an hour. But whisper-fetch.py shows me 12 values for the 12 minutes.

2. What happens when the storage is full. The data will be rewritten from the beginning?

**Comment by DanCech** [comment]
The resolution of the data is defined in the storage schema http://graphite.readthedocs.io/en/latest/config-carbon.html#storage-schemas-conf It sounds like your storage schema defines the raw interval as 60 seconds.

Yes, see the description of how retentions work in the link above.
