### ISSUE TITLE
Please publish releases to https://pypi.org

### ISSUE THREAD

**Issue by pabelanger** [graphite-project/whisper#251]
Please consider uploading releases to the Python Package Index, it is very easy way for users to then install whisper using:

  pip install whisper

It seems the namespace exists, but hasn't been used.
https://pypi.org/project/whisper/

The following provides step by step process of how to start uploads:
https://packaging.python.org/tutorials/distributing-packages/#requirements-for-packaging-and-distributing

Thanks!

**Comment by piotr1212** [comment]
It is there and has been for a long time.
```bash
$ pip install whisper                                                                                                                                                   
Collecting whisper
  Downloading https://files.pythonhosted.org/packages/bd/5c/fcf525c20f10d9bcfc83464bcd44338d86d6748600876ca79e5d95781eb3/whisper-1.1.3.tar.gz
Requirement already satisfied: six in /home/piotr/.conda/envs/py36/lib/python3.6/site-packages (from whisper)
Building wheels for collected packages: whisper
  Running setup.py bdist_wheel for whisper ... done
  Stored in directory: /home/piotr/.cache/pip/wheels/e7/1b/50/d605fd548e9215eec6f706835be2b6cf02c20235786f39536b
Successfully built whisper
Installing collected packages: whisper
Successfully installed whisper-1.1.3
You are using pip version 9.0.1, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by pabelanger** [comment]
Ah, thanks. For some reason the new UI for pypi.org confused me. The missing readme to me was it wasn't uploaded :)  Thanks for the fast reply.
