### ISSUE TITLE
Graphs past a week dont show

### ISSUE THREAD

**Issue by raptureveteran** [graphite-project/whisper#252]
I saw that this was covered through a google search but I'm not really following the solution given.

This is my storage-schemas file. Everything under 1 week works, 1 week on dont show anything.

# Schema definitions for Whisper files. Entries are scanned in order,
# and first match wins. This file is scanned for changes every 60 seconds.
#
#  [name]
#  pattern = regex
#  retentions = timePerPoint:timeToStore, timePerPoint:timeToStore, ...

# Carbon's internal metrics. This entry should match what is specified in
# CARBON_METRIC_PREFIX and CARBON_METRIC_INTERVAL settings
[carbon]
pattern = ^carbon\.
retentions = 60:90d

[icinga2_internals]
pattern = ^icinga2\..*\.(max_check_attempts|reachable|current_attempt|execution_time|latency|state|state_type)
retentions = 5m:7d

[icinga2_default]
pattern = ^icinga2\.
retentions = 1m:2d,5m:10d,30m:90d,360m:4y

[default_1min_for_1day]
pattern = .*
retentions = 60s:1d

**Comment by deniszh** [comment]
Hi @raptureveteran 
which metrics are affected by this behaviour?
According to configuration above by default you'll have 1 day of data instead of week.

**Comment by raptureveteran** [comment]
The graphs. Imgur link for an example

https://imgur.com/a/6EdKk38

I changed the storage-schemas to 

[icinga2_internals]
pattern = ^icinga2\..*\.(max_check_attempts|reachable|current_attempt|execution_time|latency|state|state_type)
#retentions = 5m:7d
retentions = 1m:2d,5m:10d,30m:90d,360m:4y

[icinga2_default]
pattern = ^icinga2\.
retentions = 1m:2d,5m:10d,30m:90d,360m:4y

and the above is the result, now suddenly i have these huge gaps.

**Comment by piotr1212** [comment]
@raptureveteran Did you manage to get your config right? I want to close this issue as I don't think this is a bug.
