### ISSUE TITLE
Make whisper commands work with graphite tag

### ISSUE THREAD

**Issue by jehutywong** [graphite-project/whisper#260]
when storing data in the use of tag, i hardly find the corresponding wsp file of a specify metric, which disables me to use the whisper commands.

**Comment by DanCech** [comment]
To find the filename for a given series:
```
from hashlib import sha256
metric = 'my;tagged=metric'
metric_hash = sha256(metric.encode('utf8')).hexdigest()
wsppath = '.'.join(['_tagged', metric_hash[0:3], metric_hash[3:6], metric_hash])
```

**Comment by piotr1212** [comment]
I don't think that is a very user friendly way. I'll reopen this issue and see if I can implement something. Can't promise any ETA, I'm quite busy at the moment.

**Comment by DanCech** [comment]
That is a simple variant of `graphite.tags.utils` `TaggedSeries.encode()` function, which could also be used if you want to import it.
