### ISSUE TITLE
rrd2whisper len(filter(...)) fails on python3

### ISSUE THREAD

**Issue by FliesLikeABrick** [graphite-project/whisper#278]
Hello,

len() on a filter() is not supported in python3, causing rrd2whisper to fail, solely because of the print() at rrd2whisper.py#161
https://github.com/graphite-project/whisper/blob/762cab790bac1f4a01ea4ff52f1e027ce2fbf195/bin/rrd2whisper.py#L161

A few options I see:
- Replace the use of filter with a list comprehension that provides the filter.  This comes with the memory tradeoff of abandoning filter()
- Change the print to use len(values) or len(timestamps) (or the lesser of the 2 if they are different for some reason), with the caveat that this overestimate will count None values that are later excluded by the filter()

If anyone can express a preference, I will add this to a PR I am working on for another tweak/fix to rrd2whisper

**Comment by piotr1212** [comment]
I'd go for the first option as it is the correct one. I don't think the memory is an issue as it is only used for a short while. And you can probably also get rid of the zip() and do everything in one comprehension.

**Comment by FliesLikeABrick** [comment]
PR #280 opened
