### ISSUE TITLE
rrd2whisper fails non-gracefully when xff not present

### ISSUE THREAD

**Issue by FliesLikeABrick** [graphite-project/whisper#279]
Hello,

rrd2whisper currently fails when xff is not defined for an RRA in the source RRD.

At line 86, xff is assumed present resulting in KeyError when it is not:
https://github.com/graphite-project/whisper/blob/762cab790bac1f4a01ea4ff52f1e027ce2fbf195/bin/rrd2whisper.py#L86

This part can be improved by setting rra_info['xff'] to None when it is not present.

Later on, this is referenced and there is no default value to use unless the user has supplied --xFilesFactor
https://github.com/graphite-project/whisper/blob/762cab790bac1f4a01ea4ff52f1e027ce2fbf195/bin/rrd2whisper.py#L112

I am happy to open a PR with improvements to this, but could use input on the suggested fix:
- Should this be handled more gracefully instead of crashing with a traceback?  The error would ideally tell the user that --xFilesFactor is required due to one or more input RRAs not containing xff
- Should the tool hard-code a default value when xFilesFactor is not available? (and ideally warn that it is being used)
- Probably slight tweaks to https://github.com/graphite-project/whisper/blob/master/README.md explaining either of the above approaches

Guidance welcome, and I'll open a PR with the necessary tweaks.

**Comment by piotr1212** [comment]
What does rrdtool do with files with no xff?

**Comment by FliesLikeABrick** [comment]
I have spent some time going through the rrdtool C code looking at default behaviors, and realized along the way that due to RRD's static file format, xff probably can't be optional -- at best (worst?) it can probably be left undefined/uninitialized by accident.

I started looking at the python bindings for rrdtool, and it looks like a bug fixed in python-rrdtool@273f2ccbdb20e4d83ff3987385d6823b6ba9d933 , pending a new release.


https://github.com/commx/python-rrdtool/commit/273f2ccbdb20e4d83ff3987385d6823b6ba9d933#diff-348b9d7f7d16c8e1d28d7b8c5202b5b2L220

I am not sure if this is a regression such that rrd2whisper used to work.

This can probably be closed, unless we wanted to update rrd2whisper to accommodate this bug more correctly

**Comment by piotr1212** [comment]
I don't think there is a sane way to handle this otherwise than printing an error message e.g. "Unknown XFF in RRD, set it manually with -x..., or update py-rrd...". 

> I am not sure if this is a regression such that rrd2whisper used to work.

Not sure how many people are actually using rrd2whisper.

Thanks for looking into this.
