### ISSUE TITLE
Unable to setup whisper 

### ISSUE THREAD

**Issue by Lavanyauppu** [graphite-project/whisper#281]
Tried to install Graphite  by following these instructions 
https://graphite.readthedocs.io/en/latest/install-source.html

When tried this step 

> python setup.py install  .

 on whisper folder  
got this exception 

```
~ whisper]$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

**Comment by piotr1212** [comment]
It is missing a dependency. `setuptools`

When installing manually you will have to manage all dependencies manually as well. So you will have to install setuptools first.

Other option which I recommend is to use `pip` which manages all dependencies for you. You wil first have to install pip (usually with your systems package manager eg. yum install pip or apt install pip) from that point you can just run `pip install .` and all dependencies will be installed by pip.
