### ISSUE TITLE
[Q] Merge not working?

### ISSUE THREAD

**Issue by shanep2300** [graphite-project/whisper#291]
Hello,

I'm trying to merge 2 different whisper directories that were created the same way. The only difference is that one was created with graphite v 1.0.2-2-b while the new one was created with graphite v 1.1.5-12. Not sure that matters at all, but that's the only difference I can see. Both should have the same retention policies and settings.

Before the merge, I was able to see both the new and old data on separate docker builds in Grafana. After the merge, whether going from new to old or old to new, resulted in the same result as only seeing the new data. Directory size would update, but none of the old data was visible.

Also, added the directory merging with svetlyak40wt@c4cf805.

**Comment by deniszh** [comment]
@shanep2300 : try to merge 2 files first to check if merge works.
Also please sure that files have same retention / archive configurations etc.
Please check both files with `whisper-info.py` and compare results.

**Comment by shanep2300** [comment]
@deniszh Ok, so I found 2 files in the same path with both info archives showing as `[{'retention': 94608000, 'secondsPerPoint': 600, 'points': 157680, 'size': 1892160, 'offset': 28}]`. Does it matter which way I merge? I would assume you'd want to merge from old data to new data?

**Comment by deniszh** [comment]
> Ok, so I found 2 files in the same path with both info archives showing as `[{'retention': 94608000, 'secondsPerPoint': 600, 'points': 157680, 'size': 1892160, 'offset': 28}]`

Please just note that `wisper-merge.py` unfortunately can't merge files with different archive configurations. But same configuration should be fine.

> Does it matter which way I merge? I would assume you'd want to merge from old data to new data?

Yes, it's copies data from first file to second one - `whisper_merge.py <from_path> <to_path>`

**Comment by shanep2300** [comment]
> Please just note that `wisper-merge.py` unfortunately can't merge files with different archive configurations. But same configuration should be fine.

That's probably my issue then. Thank you so much for taking the time to answering my questions very quickly!
