### ISSUE TITLE
[Q] - Is there any way to get list of unique Keys where time-series datapoints are available for a duration

### ISSUE THREAD

**Issue by bikashkumars** [graphite-project/whisper#298]
We are writing time-series data to graphite every second with Key and Value pair. Every hour, we are saving around 100 unique keys with different values .

There is another module in our application, which reads data from graphite using render REST API. 
There we wanted to query graphite based on key name for example x.y.z and a.b.c with specific date range to get the metrics value. 

Question:
But we wanted to get list of keys which are already available in graphite. As key names are getting changed due to some business logic. So Application, which writes metrics to graphite that generates dynamic key name.

Flow:
1. Reader Application to get of available graphite metrics keys for a date range
2. Reader App will query for a target KEY using Graphite Render Rest API

Is there any way to get the list of available KEYs ?

Note - we can't use " * " in key name - as that is creating timeout issue.

**Comment by deniszh** [comment]
Hi @bikashkumars 
You can use find API for doing this operation. Unfortunately, it's not really documented, but you can find it documented e.g. here - https://graphite-api.readthedocs.io/en/latest/api.html#the-metrics-api

PS: please open Graphite issue in graphite-web project next time, whisper is internal library, it's not directly related to API.
