### ISSUE TITLE
Whisper Resize aggregation issue

### ISSUE THREAD

**Issue by rakesh6193** [graphite-project/whisper#299]
I am noticing some issues with Whisper resizing and aggregation. I tried replicating the issue by generating a dummy whisper file and I could see the same. Not sure if we already know of it or if there is a solution. below is what I am doing.
1. Generated a new whisper file by sending data directly to graphite(version 0.9.12). Data is sent every minute and values are consecutive and lies between 1-10. The values are then repeated after every 10 mins. i.e 09:01=1, 09:02=2,... ,09:10=10, 09:11=1, .... ,09:59=9, 10:00=10 and so on for next couple of hours.
2. Then I try to resize and aggregate the file according using command --> whisper-resize.py --xFilesFactor=0.0 --aggregationMethod=average my-file.wsp 1h:10d
3. The data entering script started at 10:56 and ended at 12:35.
3. Ideally, results that I expect to see using aggregate function = average is 
For the 4 minutes from 10:56-10:59=2.5 ((1+2+3+4)/4)
For the 60 minutes from 11:00-11:59 = 5.5 (((1+2+..+10)*6)/60)
For the next 35 minutes = ~5.83

But the data after resizing is 
10:00 = 4
11:00 = 4
12:00 = 10

Not sure how is this calculated. I am seeing the similar kind of erroneous values for sum. Please help resolve.

**Please Note that I did not restart any carbon services after running resize script. Didn't see it mentioned anywhere.

**Comment by deniszh** [comment]
Hello,

What was the original retention of file before resizing?

**Comment by rakesh6193** [comment]
Hey Denis, original retention is 1m:365d..

**Comment by piotr1212** [comment]
0.9.12 is 7 years old, a lot has changed since then. There have been some issues reported about aggregation in the past but not sure if it is fixed. Best would be if you can reproduce it with the latest version. You don't need to run carbon, just use the whisper-create, whisper-update, whisper-dump and whisper-fetch cli tools to reproduce it.

**Comment by rakesh6193** [comment]
@piotr1212 Tried the way you said, results seem better but still not accurate. 

If someone can really help answer a few questions to better understand the data:
1. While using these standalone scripts, does it really matter if I am using the old version of graphite? All I am doing is - running the scripts whisper-create, whisper-update, whisper-fetch and whisper-resize on my command line. All scripts are latest taken from the update git repo.
2. How does resize work? i.e if I define 1h:1d, does the 1h start aggregating data right from the minute it is run or it takes the datapoints between formal clock hours starting from 1st minute of an hour like 11:00-11:59 or 01:00:01:59?

**Comment by deniszh** [comment]
>     1. While using these standalone scripts, does it really matter if I am using the old version of graphite? All I am doing is - running the scripts whisper-create, whisper-update, whisper-fetch and whisper-resize on my command line. All scripts are latest taken from the update git repo.

Scripts is only one part of picture - they still using whisper library. Please do not mix it up - use scripts and library from same whisper version.

>     2. How does resize work? i.e if I define 1h:1d, does the 1h start aggregating data right from the minute it is run or it takes the datapoints between formal clock hours starting from 1st minute of an hour like 11:00-11:59 or 01:00:01:59?

Whisper knows nothing about minutes or hours - it works with archives and datapoints. I can only point you to source code as source of truth in this case - https://github.com/graphite-project/whisper/blob/master/bin/whisper-resize.py
As far as I can see resize script provides some output which can be useful for debugging. So, could you please provide output of resize script in your case?

**Comment by deniszh** [comment]
Trying to reproduce, on lesser scale, to not wait for hours:
```bash
rm test.wsp && \
whisper-create.py --xFilesFactor=0.01 --aggregationMethod=average test.wsp 1:60 && \
whisper-update.py test.wsp `date -v+1S "+%s"`:1 `date -v+2S "+%s"`:2 `date -v+3S "+%s"`:3 `date -v+4S "+%s"`:4 `date -v+5S "+%s"`:5 && \
whisper-update.py test.wsp `date -v+6S "+%s"`:1 `date -v+7S "+%s"`:2 `date -v+8S "+%s"`:3 `date -v+9S "+%s"`:4 `date -v+10S "+%s"`:5 && \
whisper-update.py test.wsp `date -v+11S "+%s"`:1 `date -v+12S "+%s"`:2 `date -v+13S "+%s"`:3 `date -v+14S "+%s"`:4 `date -v+15S "+%s"`:5 && \
sleep 20 && date "+%s" && \
whisper-dump.py test.wsp && \
whisper-resize.py --xFilesFactor=0.01 --aggregationMethod=average --aggregate test.wsp 5:60 && \
whisper-dump.py test.wsp
```
So, creating file test.wsp, with "1:60" retention, putting 3 sets of digits 1..5 there, waiting 20 seconds (because we put points in the future, and whisper can't operate with datapoints in future), and then doing dump of initial file, run resize it to retention "5:60" and dumping result:

```bash
Created: test.wsp (748 bytes)
1592249308
Meta data:
  aggregation method: average
  max retention: 60
  xFilesFactor: 0.01

Archive 0 info:
  offset: 28
  seconds per point: 1
  points: 60
  retention: 60
  size: 720

Archive 0 data:
0: 1592249289,          1
1: 1592249290,          2
2: 1592249291,          3
3: 1592249292,          4
4: 1592249293,          5
5: 1592249294,          1
6: 1592249295,          2
7: 1592249296,          3
8: 1592249297,          4
9: 1592249298,          5
10: 1592249299,          1
11: 1592249300,          2
12: 1592249301,          3
13: 1592249302,          4
14: 1592249303,          5
15: 0,          0
16: 0,          0
17: 0,          0
18: 0,          0
19: 0,          0
20: 0,          0
21: 0,          0
22: 0,          0
23: 0,          0
24: 0,          0
25: 0,          0
26: 0,          0
27: 0,          0
28: 0,          0
29: 0,          0
30: 0,          0
31: 0,          0
32: 0,          0
33: 0,          0
34: 0,          0
35: 0,          0
36: 0,          0
37: 0,          0
38: 0,          0
39: 0,          0
40: 0,          0
41: 0,          0
42: 0,          0
43: 0,          0
44: 0,          0
45: 0,          0
46: 0,          0
47: 0,          0
48: 0,          0
49: 0,          0
50: 0,          0
51: 0,          0
52: 0,          0
53: 0,          0
54: 0,          0
55: 0,          0
56: 0,          0
57: 0,          0
58: 0,          0
59: 0,          0
Retrieving all data from the archives
Creating new whisper database: test.wsp.tmp
Created: test.wsp.tmp (748 bytes)
Migrating data with aggregation...
oldtimestamps: [1592249250, 1592249251, 1592249252, 1592249253, 1592249254, 1592249255, 1592249256, 1592249257, 1592249258, 1592249259, 1592249260, 1592249261, 1592249262, 1592249263, 1592249264, 1592249265, 1592249266, 1592249267, 1592249268, 1592249269, 1592249270, 1592249271, 1592249272, 1592249273, 1592249274, 1592249275, 1592249276, 1592249277, 1592249278, 1592249279, 1592249280, 1592249281, 1592249282, 1592249283, 1592249284, 1592249285, 1592249286, 1592249287, 1592249288, 1592249289, 1592249290, 1592249291, 1592249292, 1592249293, 1592249294, 1592249295, 1592249296, 1592249297, 1592249298, 1592249299, 1592249300, 1592249301, 1592249302, 1592249303, 1592249304, 1592249305, 1592249306, 1592249307, 1592249308]
(1592249011,1592249316,5)
timepoints_to_update: range(1592249011, 1592249316, 5)
Renaming old database to: test.wsp.bak
Renaming new database to: test.wsp
Meta data:
  aggregation method: average
  max retention: 300
  xFilesFactor: 0.01

Archive 0 info:
  offset: 28
  seconds per point: 5
  points: 60
  retention: 300
  size: 720

Archive 0 data:
0: 1592249285,        1.5
1: 1592249290,          3
2: 1592249295,          3
3: 1592249300,          4
4: 0,          0
5: 0,          0
6: 0,          0
7: 0,          0
8: 0,          0
9: 0,          0
10: 0,          0
11: 0,          0
12: 0,          0
13: 0,          0
14: 0,          0
15: 0,          0
16: 0,          0
17: 0,          0
18: 0,          0
19: 0,          0
20: 0,          0
21: 0,          0
22: 0,          0
23: 0,          0
24: 0,          0
25: 0,          0
26: 0,          0
27: 0,          0
28: 0,          0
29: 0,          0
30: 0,          0
31: 0,          0
32: 0,          0
33: 0,          0
34: 0,          0
35: 0,          0
36: 0,          0
37: 0,          0
38: 0,          0
39: 0,          0
40: 0,          0
41: 0,          0
42: 0,          0
43: 0,          0
44: 0,          0
45: 0,          0
46: 0,          0
47: 0,          0
48: 0,          0
49: 0,          0
50: 0,          0
51: 0,          0
52: 0,          0
53: 0,          0
54: 0,          0
55: 0,          0
56: 0,          0
57: 0,          0
58: 0,          0
59: 0,          0
```

Result looks completely sane to me, but edge cases obviously corrupted because lack of data.

Please also note how whisper creates intervals, e.g. 1592249290 interval in 5:60 retention contains points 1592249290, 1592249291, 1592249292, 1592249293 and 1592249294.
So, 
1592249285 = 1592249285..1592249289 = 1 = 1.5 (?) 
1592249290 = 1592249290..1592249294 = (2 + 3 + 4 + 5 + 1)/5 = 15/5 = 3
1592249295 = 1592249295..1592249299 = (2 + 3 + 4 + 5 + 1)/5 = 15/5 = 3
1592249300 = 1592249300..1592249304 = 2 + 3 + 4 + 5 = 4 (?)

**Comment by rakesh6193** [comment]
Hi @deniszh, I did some analysis on your data and tried to replicate with some 0 values in between and aggregate on sum and averages. And I don't think the edge cases are corrupted. Rather, Its actually the way where whisper considers different timestamps for aggregation but marks it on another timestamp. This actually makes the data look incorrect.

Taking your example: Whisper after aggregation generated values for timestamp 1592249285, 1592249290, 1592249295, 1592249300. 
However if you cross verify the data, you see for first timestamp 1592249285, it actually didn't aggregate based on 1592249285..1592249289. Rather it used 1592249286...1592249290 which makes it (1+2)/2 = 1.5 which is correct mathematically. Just that its marked on a misleading timestamp. And the 1 timestamp shift continues for all datapoints.

Intermittently, I also received results, that were perfect .i.e for timestamp **85 the aggregation was based on values from timestamp *85-*89. Not sure why.

Also, I tried replicating the same using sum as aggregation method and I see it missed by 2 timestamps. i.e for 1592419580 it aggregated values from 1592419582..1592419586 and continued till last. Below is a example output of the archive details. 


Archive 0 data:
0: 1592418381,          1
1: 1592418382,          2
2: 1592418383,          3
3: 1592418384,          4
4: 1592418385,          5
5: 0,          0
6: 1592418387,          1
7: 1592418388,          2
8: 1592418389,          3
9: 1592418390,          4
10: 1592418391,          5
11: 1592418392,          1
12: 1592418393,          2
13: 1592418394,          3
14: 1592418395,          4
15: 1592418396,          5
16: 0,          0
17: 0,          0
18: 0,          0
19: 0,          0
20: 0,          0
21: 1592418402,         10
22: 1592418403,         12
23: 1592418404,         13
24: 1592418405,         14
25: 1592418406,         15
26: 1592418407,         11
27: 1592418408,         12
28: 1592418409,         13
29: 1592418410,         14
30: 1592418411,         15
31: 0,          0
32: 1592418413,          5
33: 1592418414,          4
34: 1592418415,          3
35: 1592418416,          2
36: 1592418417,          1
37: 0,          0
38: 0,          0
39: 0,          0
40: 0,          0
41: 0,          0
42: 0,          0
43: 0,          0
44: 0,          0
45: 0,          0
46: 0,          0
47: 0,          0
48: 0,          0
49: 0,          0
50: 0,          0
51: 0,          0
52: 0,          0
53: 0,          0
54: 0,          0
55: 0,          0
56: 0,          0
57: 0,          0
58: 0,          0
59: 0,          0
Retrieving all data from the archives
Creating new whisper database: test.wsp.tmp
Created: test.wsp.tmp (940 bytes)
Migrating data with aggregation...
oldtimestamps: [1592418380, 1592418381, 1592418382, 1592418383, 1592418384, 1592418385, 1592418386, 1592418387, 1592418388, 1592418389, 1592418390, 1592418391, 1592418392, 1592418393, 1592418394, 1592418395, 1592418396, 1592418397, 1592418398, 1592418399, 1592418400, 1592418401, 1592418402, 1592418403, 1592418404, 1592418405, 1592418406, 1592418407, 1592418408, 1592418409, 1592418410, 1592418411, 1592418412, 1592418413, 1592418414, 1592418415, 1592418416, 1592418417, 1592418418, 1592418419, 1592418420, 1592418421, 1592418422, 1592418423, 1592418424, 1592418425, 1592418426, 1592418427, 1592418428, 1592418429, 1592418430, 1592418431, 1592418432, 1592418433, 1592418434, 1592418435, 1592418436, 1592418437, 1592418438]
(1592418423,1592418439,1)
timepoints_to_update: range(1592418423, 1592418439)
(1592418141,1592418446,5)
timepoints_to_update: range(1592418141, 1592418446, 5)
Renaming old database to: test.wsp.bak
Renaming new database to: test.wsp
Meta data:
  aggregation method: average
  max retention: 300
  xFilesFactor: 0.01

Archive 0 info:
  offset: 40
  seconds per point: 1
  points: 15
  retention: 15
  size: 180

Archive 1 info:
  offset: 220
  seconds per point: 5
  points: 60
  retention: 300
  size: 720

Archive 0 data:
0: 0,          0
1: 0,          0
2: 0,          0
3: 0,          0
4: 0,          0
5: 0,          0
6: 0,          0
7: 0,          0
8: 0,          0
9: 0,          0
10: 0,          0
11: 0,          0
12: 0,          0
13: 0,          0
14: 0,          0
Archive 1 data:
0: 1592418380,          3
1: 1592418385,        2.5
2: 1592418390,          3
3: 1592418395,          5
4: 1592418400,      12.25
5: 1592418405,         13
6: 1592418410,       6.75
7: 1592418415,        1.5
8: 0,          0
9: 0,          0
10: 0,          0
11: 0,          0
12: 0,          0
13: 0,          0
14: 0,          0
15: 0,          0
16: 0,          0
17: 0,          0
18: 0,          0
19: 0,          0
20: 0,          0
21: 0,          0
22: 0,          0
23: 0,          0
24: 0,          0
25: 0,          0
26: 0,          0
27: 0,          0
28: 0,          0
29: 0,          0
30: 0,          0
31: 0,          0
32: 0,          0
33: 0,          0
34: 0,          0
35: 0,          0
36: 0,          0
37: 0,          0
38: 0,          0
39: 0,          0
40: 0,          0
41: 0,          0
42: 0,          0
43: 0,          0
44: 0,          0
45: 0,          0
46: 0,          0
47: 0,          0
48: 0,          0
49: 0,          0
50: 0,          0
51: 0,          0
52: 0,          0
53: 0,          0
54: 0,          0
55: 0,          0
56: 0,          0
57: 0,          0
58: 0,          0
59: 0,          0


If you agree to the issue and if I am not missing something, Do you know of a way to resolve this? With the current script, the trends will still remain intact but they will be marked on shifted timestamps which overall remains misleading for users using it.
