### ISSUE TITLE
[Q] How to reduce the dimensionality of my data?

### ISSUE THREAD

**Issue by antocodes** [graphite-project/whisper#300]
I have data that has 5 string fields and a time stamp, which represents a type of alert being sent.
So my schema from aggregation rules looks something like: alerts.\<field1\>.\<field2\>.\<field3\>.\<field4\>.\<field5\>.total (300) = count alerts.\<field1\>.\<field2\>.\<field3\>.\<field4\>.\<field5\>.*
It all works just fine, but the amount of possible combinations for the fields is around 430 billion. Which means I can have up to 430 billion whisper files although right now I have sub 1 million due to repetition of most combinations. Is there any other way to store my non-numeric data such that I can later still filter it by each field, without having so many whisper files?

**Comment by deniszh** [comment]
@antocodes : I always liked the idea that you need to pick proper tool for the task. If you have such high cardinality data - then maybe whisper is not ideal solution for you.
You can try e.g. [graphite-clickhouse](https://github.com/lomik/graphite-clickhouse) with tags, or completely different solution - like Victoriametrics, TimescaleDB, InfluxDB or QuestDB.

**Comment by antocodes** [comment]
Thank you for the quick response. I was hoping I was missing something out since I have recently tried it out but unfortunately I might have to switch to something else.
