### ISSUE TITLE
whisper-fetch.py add option to select archive?

### ISSUE THREAD

**Issue by cdeil** [graphite-project/whisper#303]
I'm using [whisper-fetch.py](https://github.com/graphite-project/whisper#whisper-fetchpy) to extract data from a Whisper file.

At https://graphite.readthedocs.io/en/latest/whisper.html#multi-archive-storage-and-retrieval-behavior I see
> When data is retrieved (scoped by a time range), the first archive which can satisfy the entire time period is used. If the time period overlaps an archive boundary, the lower-resolution archive will be used.

Is there a way to extract the full time series for a given or each archive?

I guess I have to perfectly set `--from` and `--until` to achieve this?
Or is there a tool or API to just get a given time series in full?

**Comment by piotr1212** [comment]
Think you are looking for whisper-dump

**Comment by piotr1212** [comment]
The library already supports this. It can probably be easily added to the cmdline tool
https://github.com/graphite-project/whisper/blob/master/whisper.py#L892
