### ISSUE TITLE
Whisper should support clean dead data

### ISSUE THREAD

**Issue by TerenceYi** [graphite-project/whisper#310]
**Please ask feature request only for whisper component here, if you want to to do so for Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Is your feature request related to a problem? Please describe.**
When some metrics are tagged with k8s pod name, once pod restarted those metrics are not valid anymore. So here request a purge policy to remove those unused metrics from whisper data file.

**Describe the solution you'd like**
whisper should have a scheduler to clean dead data which last updated was extended the max retention period.

**Describe alternatives you've considered**
Currently, we create to cron job to remove those dead data file to free the disk.

**Additional context**

**Comment by deniszh** [comment]
Currently, using periodic job to remove stale files is recommended way for such task, indeed.
Solving this in library is tempting, but may be hard, hence current format is not versionable, so, you will need to some extra storage to track staleness. So, using built in OS mechanism (mtime) for that and delete file by external tool is quite natural.
Alternatively, library can provide api for metric staleness and removal and then application can call it. But internally it will call same OS-dependent functions...

**Comment by TerenceYi** [comment]
Thanks for looking into this request. The pain point from my perspective was some overdue metrics exhausted graphite disk, what I'm looking for was a recommended way to get over this. Thanks again for your info as I knew I'm following the best practice.
