### ISSUE TITLE
whisper-update read from stdin

### ISSUE THREAD

**Issue by rowlap** [graphite-project/whisper#317]
**Is your feature request related to a problem? Please describe.**
When loading values via `whisper-update`, we're limited by the maximum length of argv. As such, `xargs` or similar utilities are needed to chop up the data.

**Describe the solution you'd like**
What would be helpful instead is if `whisper-update` could read one value per line from stdin.

Happy to offer a PR for this, if desirable.

**Comment by deniszh** [comment]
Hi @rowlap ,

Yes, looks like valid use case, please do PR. Much appreciated!

**Comment by rowlap** [comment]
PR #318 submitted.

**Comment by deniszh** [comment]
Merged to master, will be released in next release.
