### ISSUE TITLE
[BUG] test_resize_with_aggregate failure

### ISSUE THREAD

**Issue by mgorny** [graphite-project/whisper#321]
**Describe the bug**
The following test is failing for me:

```pytb
======================================================================
FAIL: test_resize_with_aggregate (__main__.TestWhisper)
resize whisper file with aggregate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_whisper.py", line 838, in test_resize_with_aggregate
    self.assertEqual(len(data_low[1]), 2)
AssertionError: 10 != 2
```

**To Reproduce**

```
tox -e py37,py38,py39,py310,py311,pypy3
```

(these are all the implementations I have installed, and its failing the same way for all of them)

**Expected behavior**
Tests passing ;-).

**Environment (please complete the following information):**
 - OS flavor: Gentoo Linux
 - Graphite version: n/a, whisper: tried 1.1.8, 1.1.10, git master
 - Setup type: tried Gentoo ebuild and tox in git checkout
 - Python version: tried 3.7.13, 3.8.13, 3.9.13, 3.10.4, 3.11.0b1, PyPy3.9 7.3.9

**Additional context**
n/a

**Comment by deniszh** [comment]
Hi @mgorny 

Nit sure how this happened though - https://github.com/graphite-project/whisper/actions/runs/2367253210 and how to reproduce then.

**Comment by deniszh** [comment]
MAybe it picking up wring whisper.py smh here?
https://github.com/graphite-project/whisper/blob/master/test_whisper.py#L849

**Comment by mgorny** [comment]
I don't think that's possible, I don't have whisper installed prior to testing. Inside the venv:

```
$ type -P whisper-resize.py 
/tmp/whisper/.tox/py39/bin/whisper-resize.py
```

However, now I've found even bigger wtf: it fails when run via `tox` but passes if I run the same command inside tox's venv, i.e. (I've removed the `sh` calls in case they interfered):

```
$ tox -e py39
GLOB sdist-make: /tmp/whisper/setup.py
py39 inst-nodeps: /tmp/whisper/.tox/.tmp/package/1/whisper-1.2.0.zip
py39 installed: coverage==6.4,mock==4.0.3,six==1.16.0,whisper @ file:///tmp/whisper/.tox/.tmp/package/1/whisper-1.2.0.zip
py39 run-test-pre: PYTHONHASHSEED='3199325784'
py39 run-test: commands[0] | coverage run --branch '--include=whisper.py,test_whisper.py, bin/whisper-resize.py' test_whisper.py
................................F.........
======================================================================
FAIL: test_resize_with_aggregate (__main__.TestWhisper)
resize whisper file with aggregate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/whisper/test_whisper.py", line 838, in test_resize_with_aggregate
    self.assertEqual(len(data_low[1]), 2)
AssertionError: 10 != 2

----------------------------------------------------------------------
Ran 42 tests in 0.332s

FAILED (failures=1)
ERROR: InvocationError for command /tmp/whisper/.tox/py39/bin/coverage run --branch '--include=whisper.py,test_whisper.py, bin/whisper-resize.py' test_whisper.py (exited with code 1)
_______________________________________________________________ summary _______________________________________________________________
ERROR:   py39: commands failed
$ . .tox/py39/bin/activate
(py39) $ coverage run --branch '--include=whisper.py,test_whisper.py, bin/whisper-resize.py' test_whisper.py
..........................................
----------------------------------------------------------------------
Ran 42 tests in 0.403s

OK
```

Does it pass for you when running via `tox`?

**Comment by mgorny** [comment]
Oh, sorry, that "pass" was my mistake. I've set `TZ=UTC` to see if it's timezone related, forgot that tox doesn't pass envvars by default and then forgot that I've set it.

So it's related to timezones. If I force UTC, the test passes. With my default timezone (UTC+2), it fails. I'll submit a patch in a minute.

**Comment by mgorny** [comment]
Ping.

**Comment by deniszh** [comment]
Thanks, missed this somehow. Merged.
