### ISSUE TITLE
[Q] Did the database change between version 0.9.6 and 1.2.0?

### ISSUE THREAD

**Issue by itinneed2022** [graphite-project/whisper#323]
I'm trying to migrate an older database and its tables to a 1.2.0 setup. Reading through the documentation (1.1.10 and back) is taking awhile. So its probably quicker to ask: Is it possible to migrate an older setup's database to the newest version?

**Comment by deniszh** [comment]
Should be possible. Just apply migrations, see https://graphite.readthedocs.io/en/latest/releases/1_1_1.html#upgrading

**Comment by itinneed2022** [comment]
@deniszh How would that work with a mysql database? Running the migrations with:
PYTHONPATH=/opt/graphite/webapp django-admin.py migrate \
      --noinput --settings=graphite.settings --fake-initial

Threw an error:
django.db.utils.OperationalError: (1050, "Table 'dashboard_dashboard' already exists")

**Comment by deniszh** [comment]
MySQL should be the same. `--fake-initial` should fix issue with existing tables, so, not sure why that's happening :(

**Comment by itinneed2022** [comment]
@deniszh well it hasn't seemed to stop the graphite app from working so I guess I'll see what happens.
