### ISSUE TITLE
[Q]module 'whisper' has no attribute 'load_model'

### ISSUE THREAD

**Issue by feitgemel** [graphite-project/whisper#324]
Hi,
Try this simple python code after the Whisper setup: 

import whisper
model = whisper.load_model("base")

and get this error : "AttributeError: module 'whisper' has no attribute 'load_model'"

The whisper command CLI , works fine . This error is if I try to run in IDE

Can you help ?

Eran

**Comment by deniszh** [comment]
Hi @feitgemel,

Wrong repo, you probably mean https://github.com/openai/whisper
