### ISSUE TITLE
Add support for creating sparse files with whisper-resize (or read the configuration from carbon)

### ISSUE THREAD

**Issue by SJrX** [graphite-project/whisper#331]
**Please ask feature request only for whisper component here, if you want to to do so for Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Is your feature request related to a problem? Please describe.**
I wanted to change the retention period of a bunch of files. The instance and metrics are tuned very well and makes heavy use of sparse files to allow us to have a huge number of metrics with low disk space.

It is surprising and counter-intuitive that if you *shrink* files to truncate some of them, that your disk space can blow up because the new files aren't sparse.

**Describe the solution you'd like**
A new argument `--sparse` that causes the created files to be sparse.

**Describe alternatives you've considered**
I guess I have a work around which is just:

```
find ./ -type f -name '*.wsp' -exec echo sh -c '/opt/graphite/bin/whisper-resize.py --nobackup {} 30s:7d 5m:90d; fallocate -d {};
```

However in theory that might be twice as slow since it rewrites the file twice, although maybe fallocate is faster at this than python would be :shrug: 

**Additional context**
Carbon supports sparse creation of files here: https://github.com/graphite-project/carbon/blob/master/conf/carbon.conf.example#L205

**Comment by deniszh** [comment]
Oops, I recently did resize with sparse, but completely forgot to submit my changes. Will do when recover, got some nasty flu.
Or submit your pr if you have it.
