### ISSUE TITLE
sparse files are broken

### ISSUE THREAD

**Issue by pcn** [graphite-project/whisper#52]
https://github.com/graphite-project/carbon/issues/189

```
[utility] (graphite) pn@ip-10-155-128-120:~ $ whisper-dump.py /opt/graphite/storage/whisper/Platform2/QA/RecommendationService/i-3fbaa558/clientCall/derrida/updateContextActivations/rate/avgPerSec.wsp 1>/dev/null
Traceback (most recent call last):
  File "/usr/local/bin/whisper-dump.py", line 87, in <module>
    dump_archives(header['archives'])
  File "/usr/local/bin/whisper-dump.py", line 79, in dump_archives
    (timestamp, value) = struct.unpack(whisper.pointFormat, map[offset:offset+whisper.pointSize])
struct.error: unpack requires a string argument of length 12
```

**Comment by rowleyaj** [comment]
@SEJeff @drawks do you know if this is still an open issue? We were looking to enable the sparse setting but decided to do some research first.

**Comment by SEJeff** [comment]
I've not seen anything fixing this, but haven't been as active recently with Whisper.

**Comment by deniszh** [comment]
The case above looks like a broken wsp file. Anyway, we can close that as "non-reproducible".

**Comment by pcn** [comment]
deniszh the file was broken because sparse file support was broken.  I don't know if anyone is going to fix this (I don't have  the time  to) but if you look at the sparse file code I recall that it was clear that whisper has expectations that don't line up with using a sparse file.
