### ISSUE TITLE
Whisper could be significantly sped up O(1) complexity for aggregation.

### ISSUE THREAD

**Issue by axos88** [graphite-project/whisper#86]
Hello!

By increasing the redundancy in the data format - promote efficiency over disk space - whisper storage efficiency can be significantly improved.

When updating the lower archives currently one needs to recalculate and reaggregate all data in the upper archive.
If the data points included not only the value but also one (or multiple - as needed by the chosen aggregator) auxiliary field used by the aggregator, which would store depedning on the method whatever data is useful for it, updating the lower archives will be as easy as reading these values and updating them in O(1) complexity.
Since all updated will go down to all lower archives they will always be in sync.

This will currently only benefit the average method, but this is the most widely used right now, and opens up the possibility to add more complicated others as well (like squared average, etc.)

So instead of the current format which can be found at https://github.com/graphite-project/whisper/blob/master/whisper.py#L20,L26

While we're at it, we can also add a Magic identifier and a version information to the format.

I recommend this layout:

```

  # File = Header,Data
  # Header = Magic, Version, Metadata,ArchiveInfo+
  #              Magic = "WHISPER"
  #              Version = Version information in ascii, 5 characters "01.00"
  #     Metadata = aggregationType,aggregationMetadataSize,   maxRetention,xFilesFactor,archiveCount
  #     ArchiveInfo = Offset,SecondsPerPoint,Points
  # Data = Archive+
  #     Archive = Point+
  #         Point = timestamp,value, aggregationMetadata

```

aggregationMetadata will be of aggregationMetadataSize bytes length, and it's format will be speicific to the aggregation method chosen. The aggregationMetadataSize field is necessary so that code that does not know the aggreagtor method can still browse through the data in the archive.

**Comment by jssjr** [comment]
> There are a lot of installations of graphite out there and breaking older whisper files probably wouldn't make many of our users super keen. I'm not really sure how we could do this without breaking everything.

I believe you could implement a version field in the header by appending it after the archive info struct and updating the the data offsets accordingly in the archive info structs themselves. This would be backwards compatible and would allow the introduction of an arbitrary number of additional headers to be added.

Something like:

```
# File = Header,ExtendedHeaders,Data
#   Header = Metadata,ArchiveInfo+
#       Metadata = aggregationType,maxRetention,xFilesFactor,archiveCount
#       ArchiveInfo = Offset,SecondsPerPoint,Points
#       Version = versionInformation
#       ExtendedMetadata = aggregationMetadataSize
#   Data = Archive+
#       Archive = Point+
#           Point = timestamp,value
```

A conditional to check the distance between the archive 0 offset and the end of the header would enable newer clients to determine if they should use enhanced whisper functionality, or if they should fall back to legacy behavior (or throw an exception).

Modifying the data format is uglier because we can't rely on older clients being aware of anything but the offset into the data archive and the legacy pointFormat and pointSize values.

**Comment by jssjr** [comment]
I'm reopening this because a significant perf gain is possible and may be possible to implement in a backwards compatible manner if we're clever about how its introduced. We can close this back out and reopen a larger issue on how to extend whisper if that is preferable.

**Comment by steve-dave** [comment]
:+1:  nice!

**Comment by SEJeff** [comment]
@jssjr: Want to take a stab at this?

**Comment by piotr1212** [comment]
I'm experimenting with some performance improvements for whisper.
@axos88 : If aggregated values are stored in an auxilary field then they don't need to be reaggregated. But what I don't understand is how this value in the auxilary field would be calculated?

**Comment by axos88** [comment]
My original thought as far as i remember is that the value can only be adjusted based on the new value (for a sum the new value can be added to the sum, for average both the avg and the count needs to be stored, and then new_value = orig_value * value_count + new_value / (value_count+1).

**Comment by axos88** [comment]
So you wouldn't need to iterate through all the values in O(n), but rather can update the aggregates in O(1)
